### PR TITLE
Update plugin to work with JBake 2.6.4 - fix #2

### LINKED ISSUE #2: Maven plugin does not longer work for jbake > 2.6.1
This is due to some refactorings within jbake source.

### PR DESCRIPTION
**Pull request by bshannon**

### CODE REVIEW

**Comment by beikov** [comment]
Thanks for the contribution. I tried it, but I get a lot of warnings like:

`[WARNING] unable to load engine: java.lang.NoClassDefFoundError: groovy/text/TemplateEngine`

and finally also an error

`[ERROR] unable to instantiate ParserEngine org.jbake.parser.AsciidoctorEngine`

It doesn't process the adoc files.

**Comment by bshannon** [comment]
The warnings are due to [this JBake bug](https://github.com/jbake-org/jbake/issues/602).

I haven't seen that error, do you have a small test project that reproduces the error?

I did find another problem related to the orientdb dependency and I pushed an update.

**Comment by beikov** [comment]
You can reproduce the issues with this project: https://github.com/Blazebit/blaze-persistence
Switch the JBake version in the website project and build it.

**Comment by bshannon** [comment]
I can't reproduce it.

```
$ git diff  website/pom.xml
diff --git a/website/pom.xml b/website/pom.xml
index 872b375..d43a6e1 100644
--- a/website/pom.xml
+++ b/website/pom.xml
@@ -204,7 +204,7 @@
                 <plugin>
                     <groupId>com.blazebit</groupId>
                     <artifactId>jbake-maven-plugin</artifactId>
-                    <version>1.0.0</version>
+                    <version>1.0.1-SNAPSHOT</version>
                     <dependencies>
                         <dependency>
                             <groupId>org.jbake</groupId>
$ mvn -Djdk8.home=/opt/jdk1.8 -Dmaven.test.skip=true install
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Blazebit Blaze-Persistence ......................... SUCCESS [09:16 min]
[INFO] Blazebit Persistence Checkstyle Rules .............. SUCCESS [01:43 min]
[INFO] Blazebit Persistence Parent ........................ SUCCESS [01:34 min]
[INFO] Blazebit Persistence Core Module ................... SUCCESS [  4.384 s]
[INFO] Blazebit Persistence Core API ...................... SUCCESS [01:52 min]
[INFO] Blazebit Persistence Core Parser ................... SUCCESS [01:57 min]
[INFO] Blazebit Persistence Core Impl ..................... SUCCESS [03:42 min]
[INFO] Blazebit Persistence Integrations .................. SUCCESS [  3.640 s]
[INFO] Blazebit Persistence Integration JPA Base .......... SUCCESS [ 53.773 s]
[INFO] Blazebit Persistence Integration Hibernate Base .... SUCCESS [ 49.359 s]
[INFO] Blazebit Persistence Integration Hibernate 5.2 ..... SUCCESS [01:04 min]
[INFO] Blazebit Persistence Testsuite Base ................ SUCCESS [  2.025 s]
[INFO] Blazebit Persistence Testsuite Base JPA ............ SUCCESS [ 23.282 s]
[INFO] Blazebit Persistence Testsuite Base Hibernate ...... SUCCESS [  5.574 s]
[INFO] Blazebit Persistence Core Testsuite ................ SUCCESS [10:35 min]
[INFO] Blazebit Persistence Entity-View Module ............ SUCCESS [  2.220 s]
[INFO] Blazebit Persistence Entity-View API ............... SUCCESS [ 51.951 s]
[INFO] Blazebit Persistence Entity-View Impl .............. SUCCESS [05:30 min]
[INFO] Blazebit Persistence Entity-View Testsuite ......... SUCCESS [ 17.569 s]
[INFO] Blazebit Persistence JPA-Criteria Module ........... SUCCESS [  3.736 s]
[INFO] Blazebit Persistence JPA-2 Compatibility ........... SUCCESS [ 12.327 s]
[INFO] Blazebit Persistence JPA-Criteria API .............. SUCCESS [ 15.537 s]
[INFO] Blazebit Persistence JPA-Criteria Impl ............. SUCCESS [ 59.436 s]
[INFO] Blazebit Persistence JPA-Criteria Testsuite ........ SUCCESS [ 46.083 s]
[INFO] Blazebit Persistence Integration Hibernate 4.2 ..... SUCCESS [ 27.308 s]
[INFO] Blazebit Persistence Integration Hibernate 4.3 ..... SUCCESS [ 39.302 s]
[INFO] Blazebit Persistence Integration Hibernate 5 ....... SUCCESS [ 52.747 s]
[INFO] Blazebit Persistence Integration Hibernate 5.3 ..... SUCCESS [01:30 min]
[INFO] Blazebit Persistence Integration Hibernate 5.4 ..... SUCCESS [ 32.383 s]
[INFO] Blazebit Persistence Integration Hibernate 6.0 ..... SUCCESS [ 39.548 s]
[INFO] Blazebit Persistence Integration DataNucleus ....... SUCCESS [ 26.535 s]
[INFO] Blazebit Persistence Integration DataNucleus 5.1 ... SUCCESS [ 31.416 s]
[INFO] Blazebit Persistence Integration EclipseLink ....... SUCCESS [ 35.800 s]
[INFO] Blazebit Persistence Integration OpenJPA ........... SUCCESS [ 12.981 s]
[INFO] Blazebit Persistence Integration Entity-View CDI ... SUCCESS [ 56.275 s]
[INFO] Blazebit Persistence Integration Entity-View Spring  SUCCESS [01:15 min]
[INFO] Blazebit Persistence Integration Spring-Data ....... SUCCESS [  2.534 s]
[INFO] Blazebit Persistence Integration Spring-Data Base .. SUCCESS [ 51.387 s]
[INFO] Blazebit Persistence Integration Spring-Data 1.x ... SUCCESS [ 20.109 s]
[INFO] asm-debug-all ...................................... SUCCESS [ 54.703 s]
[INFO] Blazebit Persistence Integration Spring-Data 2.0 ... SUCCESS [03:33 min]
[INFO] Blazebit Persistence Integration Spring-Data 2.1 ... SUCCESS [01:02 min]
[INFO] Blazebit Persistence Integration Spring-Data-Rest .. SUCCESS [ 45.162 s]
[INFO] Blazebit Persistence Integration Spring-Data Testsuite SUCCESS [ 58.580 s]
[INFO] Blazebit Persistence Integration DeltaSpike Data ... SUCCESS [  2.219 s]
[INFO] Blazebit Persistence Integration DeltaSpike Data API SUCCESS [ 33.460 s]
[INFO] Blazebit Persistence Integration DeltaSpike Data Base SUCCESS [01:06 min]
[INFO] Blazebit Persistence Integration DeltaSpike Data Impl 1.7 SUCCESS [ 53.684 s]
[INFO] Blazebit Persistence Integration DeltaSpike Data Impl 1.8 SUCCESS [01:29 min]
[INFO] Blazebit Persistence Integration DeltaSpike Data Rest SUCCESS [  1.084 s]
[INFO] Blazebit Persistence Integration DeltaSpike Data REST API SUCCESS [  5.890 s]
[INFO] Blazebit Persistence Integration DeltaSpike Data REST Impl SUCCESS [ 19.418 s]
[INFO] Blazebit Persistence Integration DeltaSpike Data Testsuite SUCCESS [01:01 min]
[INFO] Blazebit Persistence Testsuite Base DataNucleus .... SUCCESS [ 19.723 s]
[INFO] Blazebit Persistence Testsuite Base EclipseLink .... SUCCESS [ 15.320 s]
[INFO] Blazebit Persistence Testsuite Base OpenJPA ........ SUCCESS [  7.038 s]
[INFO] Blazebit Persistence Documentation ................. SUCCESS [29:53 min]
[INFO] Blazebit Persistence Website ....................... SUCCESS [  6.723 s]
[INFO] Blazebit Persistence Examples ...................... SUCCESS [  1.920 s]
[INFO] Blazebit Persistence Examples Showcase ............. SUCCESS [  2.255 s]
[INFO] Blazebit Persistence Examples Showcase Base ........ SUCCESS [ 11.936 s]
[INFO] Blazebit Persistence Examples Showcase SPI ......... SUCCESS [  9.892 s]
[INFO] Blazebit Persistence Examples Showcase Fragments ... SUCCESS [  2.649 s]
[INFO] Blazebit Persistence Examples Showcase Fragments Basic SUCCESS [ 10.885 s]
[INFO] Blazebit Persistence Examples Showcase Fragments CTE SUCCESS [  5.753 s]
[INFO] Blazebit Persistence Examples Showcase Fragments Spring Data SUCCESS [ 18.746 s]
[INFO] Blazebit Persistence Examples Showcase Runner ...... SUCCESS [  1.418 s]
[INFO] Blazebit Persistence Examples Showcase Runner CDI .. SUCCESS [ 24.068 s]
[INFO] Blazebit Persistence Examples Showcase Runner Spring SUCCESS [01:04 min]
[INFO] Blazebit Persistence Examples DeltaSpike Data REST . SUCCESS [05:24 min]
[INFO] Blazebit Persistence Examples Spring Data REST ..... SUCCESS [06:35 min]
[INFO] Blazebit Persistence Archetype Parent .............. SUCCESS [  2.371 s]
[INFO] Blazebit Persistence Archetype Core Sample ......... SUCCESS [  9.108 s]
[INFO] Blazebit Persistence Archetype Entity-View Sample .. SUCCESS [  6.046 s]
[INFO] Blazebit Persistence Archetype Spring-Data Sample .. SUCCESS [  7.315 s]
[INFO] Blazebit Persistence Archetype Spring-Boot Sample .. SUCCESS [ 13.609 s]
[INFO] Blazebit Persistence Archetype DeltaSpike Data Sample SUCCESS [ 12.669 s]
[INFO] Blazebit Persistence Archetype Java EE Sample ...... SUCCESS [  7.722 s]
[INFO] Blazebit Persistence Bill of Materials ............. SUCCESS [  0.933 s]
[INFO] Blazebit Persistence Distribution Parent ........... SUCCESS [  3.149 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:53 h
[INFO] Finished at: 2019-05-17T15:20:36-07:00
[INFO] Final Memory: 126M/424M
[INFO] ------------------------------------------------------------------------
```

Did I do something wrong?

**Comment by bshannon** [comment]
@beikov  Any idea why this new plugin works for me but fails for you?

**Comment by beikov** [comment]
I'm gonna get back to you when I come back from my vacation in July.

**Comment by beikov** [comment]
Thanks! Sorry it took me so long, but I kind of forgot about this. Just tried it now and it works fine!

**Comment by beikov** [comment]
Just so you know what didn't work when I first tried it. I was lacking an asciidoctor dependency in the plugin which was included in jbake-core before it seems.
I had to adapt a few things for the new asciidoctor version, but apart from that, it all works now.
